CREATE TABLE PHONE (ID BIGINT NOT NULL, AGE INTEGER, NAME VARCHAR(50), SNIPPET VARCHAR(250), CARRIER_ID BIGINT, PRIMARY KEY (ID))
CREATE TABLE CARRIER (ID BIGINT NOT NULL, NAME VARCHAR(50), PRIMARY KEY (ID))
ALTER TABLE PHONE ADD CONSTRAINT FK_PHONE_CARRIER_ID FOREIGN KEY (CARRIER_ID) REFERENCES CARRIER (ID)
