INSERT INTO CARRIER("ID", "NAME") VALUES(0, 'AT&T')
INSERT INTO CARRIER("ID", "NAME") VALUES(1, 'Verizon')
INSERT INTO CARRIER("ID", "NAME") VALUES(2, 'T-Mobile')
INSERT INTO CARRIER("ID", "NAME") VALUES(3, 'O2')

INSERT INTO PHONE("ID", "AGE", "CARRIER_ID", "NAME", "SNIPPET") VALUES(0, 0, 3, 'Motorola XOOM(tm) with Wi-Fi', 'The Next, Next Generation. Experience the future with Motorola XOOM with Wi-Fi, the first tablet powered by Android 3.0 (Honeycomb).')
INSERT INTO PHONE("ID", "AGE", "CARRIER_ID", "NAME", "SNIPPET") VALUES(1, 1, 0, 'MOTOROLA XOOM(tm)', 'The Next, Next Generation, Experience the future with Motorola XOOM with Wi-Fi, the first tablet powered by Android 3.0 (Honeycomb).')
INSERT INTO PHONE("ID", "AGE", "CARRIER_ID", "NAME", "SNIPPET") VALUES(2, 8, 0, 'Samsung Galaxy Tab(tm)', 'Feel Free to Tab(tm). The Samsung Galaxy Tab(tm) brings you an ultra-mobile entertainment experience through its 7 inch display, high-power processor and Adobe(R) Flash(R) Player compatibility.')
INSERT INTO PHONE("ID", "AGE", "CARRIER_ID", "NAME", "SNIPPET") VALUES(3, 11, 1, 'DROID(tm) Pro by Motorola', 'The next generation of DOES.')
INSERT INTO PHONE("ID", "AGE", "CARRIER_ID", "NAME", "SNIPPET") VALUES(4, 18, 2, 'T-Mobile G2', 'The T-Mobile G2 with Google is the first smartphone built for 4G speeds on the new T-Mobile network. Get the information you need, faster than you ever thought possible.')
